timeout = 30
retry_wait_time = 5
max_retries = 6
max_concurrency = 4
include_fragments = true

base_url = "https://grafana.github.io/grafana-opentelemetry-java"

remap = [
  "https://github.com/(.*?)/(.*?)/blob/(.*?)/(.*#.*)$ https://raw.githubusercontent.com/$1/$2/$3/$4"
]

exclude = [
  "^https://github.com/grafana/grafana-opentelemetry-java/(issues|pull)/\\d+$",
  "^http://localhost",
  "^https://localhost",
  '#',
  'CONTRIBUTING.md',
  'LICENSE',
  'MAINTAINERS.md',
  "^https://github.com/grafana/grafana-opentelemetry-java/settings/",
]
