timeout = 30
retry_wait_time = 5
max_retries = 6
max_concurrency = 4
include_fragments = true

base_url = "https://github.com/grafana/grafana-opentelemetry-java/blob/main/"

remap = [
  "https://github.com/(.*?)/(.*?)/blob/(.*?)/(.*#.*)$ https://raw.githubusercontent.com/$1/$2/$3/$4"
]
